mjtakenon/hakoniwa

- app/app/Http/Controllers/Auth/Google/CallbackController.php
- app/app/Models/UserAuthentication.php
#34 でテーブルをユーザー情報と認証情報で分離したけど、google callbackでの処理に考慮漏れがありました。
一度ログインしたことがあって再ログインする場合でも `user_authentications`テーブルに書いてたのでログインするたびにデータが増えていたので、既に登録されているかを考慮するようにしています
> 既にGoogleでログインしたことある場合にはデータ登録をしないように変更

- app/package.json
Production環境のビルド時にpostcss-commentがnot foundになるため、package.jsonを更新しました
> Production環境のビルド時にpostcss-commentがnot foundになる問題の修正

- app/resources/js/components/PlanController.vue
レスポンシブ対応時に消えてしまった、プラン送信アニメーションを再度追加しました。
`isSendingPlan` の値を見てスピンアニメーションを表示・非表示にします。
既存の変数を使っているため、表示系以外に変更はありません。
レスポンシブ対応の為、合わせてボタンサイズの修正を行いました。
> プラン送信アニメーションを再度追加

- app/resources/js/components/IslandEditor.vue
- app/resources/js/components/RankingViewer.vue
- app/resources/js/components/VueHeader.vue
- app/tailwind.config.js
#46 への対応です。
うるさくならない範囲で、各種CSSアニメーションを追加しました。
スライドして上下するようにしました。
本実装がデスクトップビュー時に悪さをしないことも確認済みです。
スクロールして画面上に表示されると、左から徐々にフェードインしてくるアニメーションを実装しました。
マスを選択した際に表示されるメニューを、表示時にフェードインするようにしました。
ホバーした時のメニューについてもアニメーションを一度は実装したのですが、視認性が悪くなったのでやめました。
> 各種CSSアニメーションの追加

- app/resources/js/components/IslandEditor.vue
fix #61, fix #63
スマホビューでPlanListが意図しない動作をしてしまい、操作に支障を来す問題を解決しました。
画面リサイズの際にbreakpointの判定のため `resize` イベント時に `onWindowSizeChanged()` が発火するようになっていたのですが、スマホの実機を使っているとスクロール時にアプリのナビゲーションバーが表示されたり隠れたりする関係で、頻繁にこのイベントが呼ばれてしまい、結果としてリサイズ時のリセット処理としてHoverWindow, PlanListが非表示になっていました。
`height` が頻繁に変更されるのが問題になるため、`width` を見て条件分岐するように設定しました。
ピンチイン・ピンチアウトで `width` が変わるのではないかという懸念があったため実験しましたが、これはズームされるだけで `document.screenWidth` は変更されないため問題にならないようです。
https://github.com/mjtakenon/hakoniwa/blob/a8694bbf4b78c2b28c96119be49abb1ae7597312/app/resources/js/components/IslandEditor.vue#L215-L223
ウィンドウを固定幅に変更し、HoverWindowと同様にタップ位置に対して垂直方向に展開されるように仕様を変更しました。また左右にはみ出た際の処理についてもHoverWindowと同様のものに変更してあります。
この実装により、`Width < 230px` の端末でない限りははみ出ることはなくなりました。
（とはいえ、そんな端末があったとしても今の時代にまともに使えたものではないので考慮する必要はないかもしれませんが…） …
> スマホビューでPlanListが意図しない動作をする問題の解決

- app/resources/js/components/IslandEditor.vue
fix #73 
スマホビューの時に黒い線が入る問題を修正しました。
レスポンシブ対応時に、動的にマップのサイズが変わるように実装しましたが、画面サイズが特定のタイミングで黒い1pxの線が入るようになりました。
どうやらgridを並べるときにサイズの調整がうまくいかず、一部の列のサイズで縦幅の計算誤差が発生していたようです。
これを解消するために、rowをネガティブマージンで0.1px持ち上げることで解決しました。
> スマホビューの時、計算誤差で1pxの黒い線が入る問題を修正

- app/resources/css/app.scss
- app/resources/js/components/LogViewer.vue
- app/resources/views/pages/index.blade.php
ログ表示部を見やすいようにデザイン変更しました。
特にスマホビューで読みづらい問題を解決しました。
ログ表示部の背景色を追加し、ヘッダーに色を付けました。
また各ログに対して下線を引くことで境界が分かりやすくなっています。
加えてスマホビューでのmargin微調整や、テキストサイズの修正を行い大幅に可読性が向上しました。
**Desktop**
**Smartphone**
まだログのテキスト関係には手を付けていませんが、テキストの色や表示方法を変更するにあたり、大幅にバックエンド側にも修正加える必要があります。
現在新機能の実装に伴いログ実装部を修正中とのことですので、一旦こちらの修正は保留します。
> ログ表示部を見やすいようにデザイン変更

- app/resources/js/components/StatusTable.vue
fix #84 
島編集画面で、スマホビューの時文字が溢れる問題を修正しました。
今まで数字が大きくなると読みづらかったので、`,` の区切りも追加しています。
JavascriptのNumber型の最大値、`9007199254740991` まで正常に動作します。
レイアウトも多少調整しています。
**Smartphone**
**Desktop**
特殊な方法でないと実装できないため、かなり大掛かりに修正しています。
Vueが完全にレンダリングされた後でないと、v-for内のrefを取得しようとしたときに参照先が見つからないため、$nextTickを使用してレンダリング後にサイズ調整がかかるように変更しています。
またサイズに関しては、環境によってフォントが違うことで横幅の計算が変わってしまうことから、`calcFontSize` にて仮のspanを生成してbodyにappendしたのちにサイズの計測、計算後に削除するように変更しています。
Tailwindのテキストサイズ関係のクラスが今回の用途では使いづらいため、styleで直指定しています。
スマホビューとデスクトップビューでレイアウトが変更される関係でmaxWidthの計算も異なるため、IslandEditorにあったウィンドウサイズ変更時の処理についても実装を移植しました。
> 島編集画面のステータス数値のフォントサイズを動的に変更するよう修正

- app/resources/js/components/LogViewer.vue
新しいログ表示でWQHDなどの高解像度ディスプレイを使っていると、レイアウトが崩れてしまう問題を修正しました。
一部`vw`単位で指定していた箇所があったのですが、documentのサイズが広がるにつれて割合がずれていくのに対してログ表示のwidthはmaxサイズが固定だったためずれてしまいました。
> WQHDなどの高解像度でログのレイアウトが崩れる問題の修正

- app/resources/js/components/CountdownWidget.vue
- app/resources/js/components/LogViewer.vue
- app/resources/js/components/StatusTable.vue
Device Pixel Ratioが1.0以上の端末で開いたとき、font-sizeの指定でpx単位で指定している箇所が小さくなりすぎるバグを修正しました。
特にiOS・Android端末でfont-sizeの指定に限り、dpx比>1の端末でフォントサイズが予期せぬサイズになっていました。
他の要素についてはきちんとスケーリングされて表示されるため、rem指定でなくても問題ないようです。
一旦全てのVueコンポーネントのfont-sizeがpx指定になっている箇所を修正しましたが、他にもまた問題が見つかれば修正します。
> dpx比が1.0以上のデバイスでテキストが小さくなりすぎる問題の修正

- app/app/Http/Controllers/Api/Islands/DetailController.php
- app/app/Http/Controllers/Api/Islands/PlansController.php
- app/app/Http/Controllers/Api/WebApi.php
- app/app/Http/Controllers/Web/Accounts/IndexController.php
- app/app/Http/Controllers/Web/Auth/Google/CallbackController.php
- app/app/Http/Controllers/Web/Auth/Google/RedirectController.php
- app/app/Http/Controllers/Web/Auth/YahooJapan/CallbackController.php
- app/app/Http/Controllers/Web/Auth/YahooJapan/RedirectController.php
- app/app/Http/Controllers/Web/Help/IndexController.php
- app/app/Http/Controllers/Web/Islands/BbsController.php
- app/app/Http/Controllers/Web/Islands/DetailController.php
- app/app/Http/Controllers/Web/Islands/PlansController.php
- app/app/Http/Controllers/Web/Logout/IndexController.php
- app/app/Http/Controllers/Web/Register/IndexController.php
- app/app/Http/Middleware/Authenticate.php
- app/resources/js/store/MainStore.ts
- app/routes/api.php
- app/routes/web.php
- 島の地形のみをJSONで取得するAPI、`GET /api/islands/{island_id}`を追加しました。
- 計画送信API`PUT /islands/{island_id}/plans`は、`PUT /api/islands/{island_id}/plans`にリネームしました。
- 未ログイン時は403レスポンスを返すように修正しました。
> Controllerの中でAPIを分離、未ログイン時のAPIは403を返すよう修正

- app/resources/js/components/IslandEditor.vue
- app/resources/js/components/IslandPopup.vue
- app/resources/js/components/PlanController.vue
- app/resources/js/pages/PlanPage.vue
- app/resources/js/store/Entity/Island.ts
- app/resources/js/store/MainStore.ts
resolve #54
ポップアップ表示で島を表示する機能を実装しました。
目標の島の「開く」ボタンを押したとき、これまではIslandViewが開くようになっていましたが、
ページ遷移せずajax通信を行い、ポップアップで表示、ミサイルを打てる機能を実装しました。
怪獣やスライムなどが複数マスに存在する場合が想定されるため、敢えてミサイルのプラン選択後もウィンドウを閉じないような設計にしています。ポップアップウィンドウ外もしくはウィンドウ右上の×ボタンを押すと消える仕様になっています。
実装に合わせてPiniaのstoreにも変更をかけてあります。
また現状ではIslandEditor内で別の島にミサイルを送っていても、自分の島の座標にisReferencedが立つ仕様になっていたためそれも修正しました。
> ポップアップ島表示機能の実装

- app/resources/js/components/RankingViewer.vue
ランキング表示のレイアウトで、mdかつlgの直前の場合、開発ポイントなどが数千万ptsを超えた場合レイアウトが崩れていたのを修正しました。
具体的には以下2点の修正を行いました。
- **画面サイズがmd以上lg未満の時、gridのレイアウトを横3列に変更・フォントサイズの変更**
- 今回の主要な修正です。一部の場合においてレイアウトを変えることで文字が溢れるのを防ぎます。
- **当該箇所についてCSSのクラス化を行い、`nth-of-type`で指定するようにリファクタ**
- **島名の文字長に応じて文字サイズの調整**
- 上記2点の修正時に発見したのですが、文字サイズを小さくしないとステータス表示の下に不自然な余白ができてしまうため修正を行いました。
> md:max-lgの時のレイアウト変更、島名が長い時にフォントサイズを縮小

- app/app/Http/Controllers/Api/Islands/CommentsController.php
- app/app/Http/Controllers/IndexController.php
- app/app/Http/Controllers/Web/Islands/DetailController.php
- app/app/Http/Controllers/Web/Islands/PlansController.php
- app/app/Models/Island.php
- app/app/Models/IslandComment.php
- app/database/factories/IslandFactory.php
- app/database/factories/UserFactory.php
- app/database/migrations/2023_05_20_0220301_create_island_comments.php
- app/phpunit.xml
- app/routes/api.php
- app/tests/App/Http/Controllers/Api/Islands/CommentsControllerTest.php
- app/tests/App/Http/Controllers/Web/Register/IndexControllerTest.php
- オーナーコメントを保存するDBテーブルを追加しました
- コメントの編集APIを追加しました
- エンドポイントは `POST /islands/{island_id}/comments` です
- 島の情報と併せてcommentsを返すようにしました
- トップページ、島詳細画面（`/islands/{island_id}`）、島編集画面（`/islands/{island_id}/plans`）です
> オーナーコメントの変更APIと取得部分のコントローラを実装

- app/resources/js/components/VueHeader.vue
- app/resources/js/store/Entity/Theme.ts
CSSが読み込まれないバグの修正をしました。
localStorageの判定がgetItemsしたときにnullが帰ってくるのですが、誤ってundefinedで判定していました。
ブラウザの仕様違いが怖いので、一応undefiendも残してあります。
ついでに間違っていたdefaultThemeも直しておきました。
> CSSが読み込まれないバグの修正

- app/app/Http/Controllers/Api/Islands/DetailController.php
- app/app/Http/Controllers/Web/Register/IndexController.php
- app/resources/js/components/IslandNameSettings.vue
- app/resources/views/pages/register.blade.php
島の登録時と、情報変更時に島名・オーナー名で重複していた場合、今までは500サーバーエラーを返していました。
登録時はエラーメッセージと共に登録画面にリダイレクトし、変更時は400 bad requestとエラーレスポンスコードを返すよう修正しました。
> 島・オーナー名の重複時バリデーションの追加とエラー表示の修正

- app/resources/js/components/IslandNameSettings.vue
`/settings` 画面を作った際、島の名前設定の末尾に「島」が表示されていませんでした。
`/register` ページと同様に末尾に「島」を表示するようにしました。
> 島名の設定画面で末尾に「島」を表示

- app/resources/css/app.scss
- app/resources/css/themes.scss
- app/resources/js/components/IslandEditor.vue
- app/resources/js/components/PlanController.vue
- app/resources/js/components/PlanList.vue
- app/resources/js/components/VueHeader.vue
- app/resources/js/pages/PlanPage.vue
フロントのデザインを複数個所修正しました。
元々ログ表示が画面下に張り付かないように `#app` に対してborder-bottomを付けていたのですが、フッターの下に余白が発生していたので修正しました。
ヘッダーのアイコンをFontAwesomeに変更しました。直書きのSVGは削除済みです。
変更に伴い、少しCSSにも修正が入っています。
また以前話題に出ていた島編集ボタンをわかりやすくするための文字を表示しました。
当初の想定では「自分の島へ」という文言を使う予定でしたが、いざ置いてみると自分の島で何があるのか？というのがプレイ済みでないと意図を汲み取れないので「島を開発」というタイトルにしました。気に入らなかったら修正してください。
FullHDの半分の画面の時、2段構成になってしまうのが気に入らなかったので直しました。
`PlanController` と `PlanList` を縮めましたが、さほど問題にはならないと思います。
- **before**
- **after**
bodyの子要素以下のスクロールバーのデザインを変更しました。
Firefoxのスクロールバーは変更していないのですが、FirefoxはChromeと違い初期状態でいい感じのデザインになっていたので特に変えないつもりです。
PlanListのスクロールについてもDOM要素のスクロールを当てる箇所を見直してきれいになりました。
> フロントのデザインを複数個所修正

- app/resources/js/components/IslandEditor.vue
島編集画面の処理を修正し、スクリプト実行パフォーマンスを改善しました。
島編集画面について、指定タイルの地形情報を取得する`getIslandTerrain`関数は、Arrayのfilterを使って実装していました。
filterの計算量はO(n)であり、それをv-forで描画している各タイルに対して行っているため、何かしらアクションを起こした場合の計算量がO(n^2)となっており、処理が低速な状態でした。
store.terrainsのデータは現在readonlyであり、更新はしない（これからする予定もない）想定なので、`IslandEditor.vue`にterrainsをローカル変数という形で二次元配列にキャッシュしました。これにより、`getIslandTerrain`はO(1)で実行できるため、以前と比べて高速になったと思います。
chromeのパフォーマンス測定機能を利用し、同じ操作を行いパフォーマンスを測定しました。
スクリプト実行にかかる時間が2810ms→617msと、大幅に改善していることがわかります。
修正前パフォーマンス測定結果（sta環境で測定）
修正後パフォーマンス測定結果（local環境で測定）
> IslandEditorのgetIslandTerrainをfilterでなくarrayで返すよう修正

- app/resources/js/components/StatusTable.vue
iOSで島編集画面のタイルをタップした時に出てくるメニューが非常に重い問題を解決しました。
fixed #129 
以前にフォントサイズ変更の仕様変更で使用したContainer Queryが原因でした。
そのため直接的な原因は島編集画面ではなく、`StatusTable.vue` のほうでした。
かといって以前の仕様に戻すとまたメモリリークが起きてしまうため、実装をまた大幅に変更しました。
fontSizeを用意しておき、DOM要素がレンダリング後（this.$nextTick）にコンテナのサイズを計算して調整しています。
v-bindからmethodを直接呼び出しているわけではなく、あくまでscreenWidthの変更を検知して再計算が走るので計算コストもそこまで重くないはずです。
ただ実装がレスポンシブベースではあるものの、StatusTableの発展ポイント～資源生産の個所のレイアウトを今後大幅に変更した場合は崩れる可能性があります。
たぶんこれが最適解だと思いますが、もしもっと改善案が浮かんだら再度修正するかもしれません。
> iOSで島編集メニューが重い問題の解決

- app/app/Entity/Cell/Ship/Battleship.php
- app/app/Entity/Log/LogRow/ReceiveBountyLog.php
- app/composer.json
- app/composer.lock
- app/database/seeders/RegisterIslandSeeder.php
- app/tests/App/Scnario/NextTurn.php
- infra/app/Dockerfile
- 海賊を倒したときに懸賞金がもらえるよう処理を追加しました
- 埋蔵金と同じで100億円〜1000億円の範囲です
- ついでにER図作成ライブラリをログがうるさかったので削除しました
> 海賊を倒したとき懸賞金がもらえるよう処理を追加

- app/resources/css/app.scss
- app/resources/js/components/CommentForm.vue
- app/resources/js/components/LogViewer.vue
- app/resources/js/components/RankingViewer.vue
- app/resources/js/components/StatusTable.vue
- app/resources/js/pages/PlanPage.vue
- app/resources/js/pages/SightseeingPage.vue
- app/resources/views/pages/index.blade.php
- app/tailwind.config.js
デザインに関する修正を行いました。
見た目の変更というより、iOS対応のための処理方法の変更が中心です。
島が登録されていないとき空白が表示されたりしてデザインがあまりよくなかったため、修正を行いました。
- RankingViewer
「島が登録されていません」という表記が出るように変更
- LogViewer
ログがないときは表示しないように実装を変更
ランキングのデザイン修正を行いました。
- 億円の表記がlg:で縦書きになってしまい、それに引っ張られて値がずれる問題の修正
- md:max-lg:の時、「資源」のセクションの右側にborderが表示されずバランスが悪くなっていたため修正
- ボックスの角丸のRを微調整
- 島編集・閲覧画面でmd:max-lg:の時に左右にパディングが発生するように変更
- max-md:の時のコメント入力欄のデザイン変更
- max-md:にてx軸に不要なスクロールバーが表示される問題の修正
- 以前デバッグ時に追加したものが残っていたようです。すいません。
本PRの一番大きい修正箇所です。
iOSデバイスでTailwindのdrop-shadowが機能しない問題を修正しました。
LogViewerとRankingViewerそれぞれ異なる要因でこの問題が発生していました。
iOSデバイスでは `overflow-hidden` と `drop-shadow` が同時にアタッチされているとき、overflowした分の影が切り取られてしまうため、四隅の角以外の影が表示されないようなおかしな表示になっていました。
本来親要素のroundedに合わせてoverflow: hiddenで切り取りたいところではありますが、LogViewerの `.subtitle` …
> デザイン修正およびiOSに起因する問題の解決

- Makefile
- app/app/Console/Commands/ExecuteTurn.php
- app/app/Entity/Cell/IHasMaintenanceNumberOfPeople.php
- app/app/Entity/Cell/MaintenanceInfo.php
- app/app/Entity/Cell/MissileFireable/MissileBase.php
- app/app/Entity/Cell/MissileFireable/SeabedBase.php
- app/app/Entity/Cell/Ship/Battleship.php
- app/app/Entity/Cell/Ship/TransportShip.php
- app/app/Entity/Status/Status.php
- app/app/Entity/Terrain/Terrain.php
- app/app/Http/Controllers/IndexController.php
- app/app/Http/Controllers/Web/Islands/DetailController.php
- app/app/Http/Controllers/Web/Islands/PlansController.php
- app/app/Http/Controllers/Web/Register/IndexController.php
- app/app/Models/IslandStatus.php
- app/composer.json
- app/composer.lock
- app/database/factories/IslandStatusFactory.php
- app/database/migrations/2023_06_09_211255_alter_island_statuses_table.php
- 他島に派遣した艦船の維持人数は計算されない仕様でしたが、この度正しく計算されるようになりました
- この値はDBに保存するようにしており、コントローラに返す値にも含めました
- ついでに油田が環境に影響せず工場を建てると通常になるバグも修正しました
> 維持人数の計算方法修正

- app/resources/js/components/AchievementIcons.vue
- app/resources/js/components/CommentForm.vue
- app/resources/js/components/StatusTable.vue
- app/resources/js/pages/PlanPage.vue
- app/resources/js/pages/SightseeingPage.vue
- app/resources/js/store/Entity/Status.ts
- app/resources/js/store/MainStore.ts
100年ぶりぐらいにやりかけのPRを思い出したので実装
直近でReactを触る予定があるので、記憶が汚染される前にやりました
resolve #143 
全体的にレイアウトを変更しています。
- アイコンを追加してUXを向上しました
- 複雑になりすぎたこと・計算量が一気に増えてしまったため、フォントサイズの調整をbreakpointベースの決め打ちに戻しました
- 島の概要（発展ポイント等）、島の情報（資源等）、人的資源の状況で3セクションに分けて視認性を上げました。
- 軍事の維持人数を表示できるようにstoreの変更、表示部の追加
- 総人口 - 各維持人数を計算し、未割当の人数を表示
- 未割当が1以上の時、表示枠や文字がerror色になる機能の実装
スクショにはありませんが、ダークテーマも確認・調整済みです。
久々だったのでバグないか念入りにチェックしたので、恐らく大丈夫なはず…
> 島ステータスのリニューアル

- .editorconfig
- app/.editorconfig
- app/.prettierignore
- app/.prettierrc.js
- app/package.json
- app/yarn.lock
- prettierを導入および `.prettierrc`, `prettierignore` の設定
- tailwindcssのprettier pluginを導入・設定しました
- package.jsonに実行用のコマンド追加
- EditorConfigを一部ルートディレクトリに移動、PHP用フォーマット設定が `[*]` になっていたため変更
> Prettierのセッティング・.editorconfigの再設定

- app/resources/js/app.ts
- app/resources/js/bootstrap.ts
- app/resources/js/components/layout/DebugTools.vue
- app/resources/js/components/pages/Releases/ReleasesMarkdown.vue
- app/resources/js/components/pages/Releases/ReleasesPage.vue
- app/resources/js/components/pages/Settings/SettingsInfo.vue
- app/resources/js/components/pages/Settings/SettingsPage.vue
- app/resources/js/components/pages/Settings/SettingsTheme.vue
- app/resources/js/debug.ts
- app/resources/js/declarations/markdown-it-sanitizer.d.ts
- app/resources/views/components/header.blade.php
Settings, Releasesページ関連のComposition API化およびリファクタを行いました。
- SettingsPage.vue
- SettingsTheme.vue
- StatusInfo.vue
- ReleasesPage.vue
- ReleasesMarkdown.vue
リファクタリングのために以下の軽微な修正を含んでいます。
- SettingsTheme.vue
- CSSセレクタの修正
- SettingsPage.vue
- Typescriptのstrict対応のため、`store.$patch`処理を `(state) => {}` で修正する方式に変更
- ReleasesMarkdown.vue
- `@ts-ignore` が納得いかないので、自前で `markdown-it-sanitizer.d.ts` の型定義ファイルを作成
- `js/declarations` 内にありますが、ディレクトリ構成が納得いかなかったら変更します
その他、軽微なバグ修正を含みます。
Vite 5.xへの更新により内部の Rollup が4系に更新されたのですが、その対応のために `CompilerOptions.moduleResolution` を `nodenext` に変更しました。
`node16` 以降の設定を使った場合、 `import` 文でインポートするファイルの拡張子を省略しないような決まりになっているようで、IDE上でエラーが発生するようです。今回記述したコードについては一通り修正してあります。
今の所Javascriptへのビルドでこのエラーがあっても問題はないようですが、IDEのアラートがごちゃごちゃになるので早めに解決しておきたいです。 …
> Settings, Releasesページのリファクタおよびバグ修正

- frontend/src/js/entity/Achievement.ts
- frontend/src/vue/components/ui/AchievementIcons.vue
実績のアイコンホバー時に他の島の情報を取ってきてしまう問題を修正しました。
`Achievement.ts` 内の処理でAchievementListから取得したテンプレートを基に展開していたのですが、**人類は愚か**なのでそのまま参照を書き換えるとかいうとんでもないミスをしていました。 `structuredClone()` を使用することで解決済みです。
その他に `AchievementIcons.vue` の `achievements` を `ref` に変更しました。こちらは一応現状のコードでも問題ないのですが、将来的に実績周りの更新処理でリアクティブにならない問題を起こしそうなので、合わせて変更してあります。
fixed #169
> 実績のアイコンホバー時に、他の島の情報を取ってきてしまう問題の修正

- frontend/src/vue/pages/Islands/Plans/PlansController.vue
Storeの構造変更に伴い、「全荒地に整地入力」といった全xxに入力系が動作していない問題を修正しました。
fixed #170
> PlansControllerで全xxに入力系が動かないバグの修正

- frontend/package.json
- frontend/src/js/bootstrap.ts
- frontend/src/js/store/IslandEditorStore.ts
- frontend/tsconfig.json
Store分割バグの問題があったため、一旦tscでチェックをかけました。
エラーになっていた箇所は修正済みです。ビルドも問題なく行えています。
- チェック用コマンドを `package.json` に追加
- tsconfig.jsonの修正
- `module` の設定が誤っていた問題を修正
- tscがnode_modules内を含んでしまったため、 `skipLipCheck` オプションを追加
- `IslandEditorStore.ts` の変数名の誤りを修正
- `bootstrap.ts` の修正
- 使用していない `window.axios` を削除
- importのfromに `.js` が欠けていたため追加
> tscによるチェックと修正

- infra/cloudbuild/develop.yaml
WebサーバーとDBがus-centralでリージョンをまたいでおり
ターン更新にアホ時間かかっている為移したい所存
ついでにイメージの保存場所もリージョンを合わせて起動時間短縮を図っている
> Cloud Run Jobsをus-central1リージョンに移行
